- hosts: localhost
  connection: local

  vars_files:
    - settings.yml

  tasks:
    # Setup
    - name: Determine Mac machine type
      set_fact:
        is_apple_silicon: "{{ ansible_machine == 'arm64' }}"

    - name: Print and exit if not apple silicon
      debug:
        msg: "This playbook is only for Apple Silicon machines."
      when: not is_apple_silicon
      failed_when: not is_apple_silicon

    # Configure user
    - name: Configure user
      import_tasks: roles/common/tasks/configure-user.yml
      when: user.configure

    # Install Homebrew
    - name: Install Homebrew 
      import_tasks: roles/common/tasks/install-homebrew.yml
      when: homebrew.install_homebrew

    - name: Install Rosetta 2
      import_tasks: roles/common/tasks/install-rosetta.yml
      when: user.install_rosetta

    # Install packages
    - name: Install Mise
      import_tasks: roles/common/tasks/install-mise.yml
      when: homebrew.install_homebrew and mise.install_mise

    - name: Install Homebrew packages
      import_tasks: roles/common/tasks/install-homebrew-packages.yml
      when: homebrew.install_homebrew and homebrew.install_packages

    - name: Finish
      debug:
        msg: Install is complete, exit your terminal completely and re-open it for changes to apply.