user:
  configure: true
  install_p10k_theme: true # If you do this, you'll want to install a nerd font to your terminal.
  install_home_files: true # This will copy the files in the files/user-home directory to the user's home directory.

homebrew:
  homebrew_location: /opt/homebrew
  install_homebrew: true

asdf:
  configure_global_tool_versions: true # This will copy the .tool-versions file to the user's home directory.
  plugins:
    # If you add something here, you will need to build a task to install it with ASDF too.
    - name: direnv
      version: 2.36.0
    - name: nodejs
      version: 22.15.0
    - name: python
      version: 3.13.3
    - name: yarn
      version: 1.22.19
    - name: kubectl
      version: 1.28.2
    - name: kubectx
      version: 0.9.5