- name: Download ohmyzsh to tmp dir
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh
    mode: 0755

- name: Install ohmyzsh for '{{ ansible_user_id }}'
  become: true
  command:
    cmd: 'su - {{ ansible_user_id }} -c "/tmp/zsh-installer.sh \"\" --unattended"'
    creates: /Users/{{ ansible_user_id }}/.oh-my-zsh

- name: Install powerlevel10k for '{{ ansible_user_id }}'
  become: true
  command:
    cmd: 'su - {{ ansible_user_id }} -c "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /Users/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel10k"'
    creates: /Users/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel10k
  when: user.install_p10k_theme

- name: Remove generated .zshrc
  file:
    path: roles/common/files/user-home/.zshrc
    state: absent

- name: Build .zshrc
  template:
    src: "../templates/.zshrc.j2"
    dest: "roles/common/files/user-home/.zshrc"

- name: Add home files to '{{ ansible_user_id }}'
  copy:
    src: "{{ item }}"
    dest: "/Users/{{ ansible_user_id }}/{{ item | basename }}"
    owner: '{{ ansible_user_id }}'
    mode: '644'
  with_fileglob:
    - "../files/user-home/.*"
    - "../files/user-home/*"
  when: user.install_home_files
