- name: Get package version
  set_fact:
    package_version: "{{ asdf.plugins | selectattr('name', 'equalto', 'kubectl') | map(attribute='version') | first }}"

- name: Add kubectl to ASDF
  command:
    cmd: '{{ homebrew.homebrew_location }}/bin/asdf plugin add kubectl https://github.com/asdf-community/asdf-kubectl.git'
    creates: '/Users/{{ ansible_user_id }}/.asdf/plugins/kubectl'

- name: Install kubectl {{package_version}}
  command:
    cmd: '{{ homebrew.homebrew_location }}/bin/asdf install kubectl {{package_version}}'
    creates: '/Users/{{ ansible_user_id }}/.asdf/installs/kubectl/{{package_version}}'