- name: Get package version
  set_fact:
    package_version: "{{ asdf.plugins | selectattr('name', 'equalto', 'python') | map(attribute='version') | first }}"

- name: Add python via ASDF
  command:
    cmd: '{{ homebrew.homebrew_location }}/bin/asdf plugin add python'
    creates: '/Users/{{ ansible_user_id }}/.asdf/plugins/python'

- name: Install python {{package_version}}
  command:
    cmd: '{{ homebrew.homebrew_location }}/bin/asdf install python {{package_version}}'
    creates: '/Users/{{ ansible_user_id }}/.asdf/installs/python/{{package_version}}'