- name: Get package version
  set_fact:
    package_version: "{{ asdf.plugins | selectattr('name', 'equalto', 'nodejs') | map(attribute='version') | first }}"

- name: Add nodejs via ASDF
  command:
    cmd: '/Users/{{ user.username }}/.asdf/bin/asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git'
    creates: '/Users/{{ user.username }}/.asdf/plugins/nodejs'

- name: Install nodejs {{package_version}}
  command:
    cmd: '/Users/{{ user.username }}/.asdf/bin/asdf install nodejs {{package_version}}'
    creates: '/Users/{{ user.username }}/.asdf/installs/nodejs/{{package_version}}'