- name: Install Homebrew packages
  community.general.homebrew:
    name: '{{ item.name }}'
    state: present
    path: '{{ homebrew.homebrew_location }}/bin'
  loop: '{{ homebrew.packages }}'
  when: homebrew.packages is defined