- name: Get package version
  set_fact:
    package_version: "{{ asdf.plugins | selectattr('name', 'equalto', 'yarn') | map(attribute='version') | first }}"

- name: Install dependencies
  command:
    cmd: '{{ homebrew.homebrew_location }}/bin/brew install gnu-tar gpg'
    creates: '/usr/bin/gpg'
  when: homebrew.install_homebrew

- name: Add yarn via ASDF
  command:
    cmd: '{{ homebrew.homebrew_location }}/bin/asdf plugin add yarn'
    creates: '/Users/{{ ansible_user_id }}/.asdf/plugins/yarn'

- name: Install yarn {{package_version}}
  command:
    cmd: '{{ homebrew.homebrew_location }}/bin/asdf install yarn {{package_version}}'
    creates: '/Users/{{ ansible_user_id }}/.asdf/installs/yarn/{{package_version}}'